### ISSUE TITLE
Make callbacks executable (if desired) outside the interrupt routine.

### ISSUE THREAD

**Issue by TrLucas** [LuTri/AVRClock#2]
## Background ##
Currently, the configured callbacks for a countdown are executed **inside** the corresponding interrupt routine, which exposes critical failure potential when another countdown follows (and would be finished before the active)

## What to change ##
* change `prepare_countdowns()` and `prepare_single_countdown()` to accept a param, whether a callback should be run inside an interrupt routine or not.
* Implement a function `can_run_callback()`, exposed publicly, which should return whether or not a callback can be executed (i.e the corresponding countdown for a callback has finished)
* Implement a function `get_current_callback()`, exposed publicly, which returns the callback of the latest finished countdown.

### Note:
This does not prevent the aforementioned error-scenario, but gives developers more freedom to judge and act on time-heavy calbacks.

**Comment by LuTri** [comment]
We won't implement a function `can_run_callback()` - we'll just return NULL in `get_current_callback()` instead.
